# Generated by Django 4.2.6 on 2023-11-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_and_access_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedpasswordresetotpattemps',
            name='last_failed_attempt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
