# Generated by Django 4.2.6 on 2023-11-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_and_access_management', '0003_rename_failedpasswordresetotpattemps_failedpasswordresetotpattempts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetotp',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='created_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
