# Generated by Django 4.2.6 on 2023-11-26 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication_and_access_management', '0004_rename_user_id_passwordresetotp_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryBlockUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_at', models.DateTimeField(auto_now_add=True)),
                ('unblock_at', models.DateTimeField()),
                ('reason', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
