# Generated by Django 4.2.6 on 2023-11-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_and_access_management', '0005_temporaryblockuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryblockuser',
            name='block_at',
            field=models.DateTimeField(),
        ),
    ]
