# Generated by Django 4.2.6 on 2023-11-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0002_follow_unique_follow_pair'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('follower', models.F('followed')), _negated=True), name='could_not_follow_itself'),
        ),
    ]
